solana: emit cpi
wormholelabs-xyz/example-messaging-endpoint pull request #37
Opened 2024-11-01 09:52 UTC by bingyuyap

2024-11-01 10:03 UTC, bingyuyap commented on svm/programs/mock-integrator/Cargo.toml
> +solana-logger = "=2.0.2"
dont need this

2024-11-01 10:03 UTC, bingyuyap commented on svm/programs/mock-integrator/Cargo.toml
> +anchor-lang = { workspace = true, features = ["event-cpi"] }
dont need this either

2024-11-01 19:35 UTC, evan-gray requested changes

2024-11-01 19:35 UTC, evan-gray commented on svm/package-lock.json
Did you intend to switch to npm in this commit? looks like you mistakenly ran `npm i` instead of `yarn add`

2024-11-01 19:35 UTC, evan-gray commented on svm/package.json
> +    "ts-results": "^3.3.0"
it looks like this package is only used in one place. what was the benefit of adding it? Surely there was a TS native way to accomplish the same thing.

2024-11-01 19:35 UTC, evan-gray commented on svm/tests/router.ts
> +export async function expectIxOk(
seems like this and `debugSendAndConfirmTransaction` could be better re-written with `async/await` in place of `ts-results`.

2024-11-01 19:35 UTC, evan-gray commented on svm/programs/router/src/utils/constants.rs
> +pub const SOLANA_CHAIN_ID: u16 = 1;
this code will not only be used for Solana. Could we just call this `CHAIN_ID` and either make this a compile time argument or a feature flag?

2024-11-01 19:35 UTC, evan-gray commented on svm/programs/router/src/instructions/update_admin.rs
> +/// Emits an `AdminUpdated` event
where does the event get emitted?

2024-11-01 19:35 UTC, evan-gray commented on svm/programs/router/src/utils/constants.rs
> +pub const SOLANA_CHAIN_ID: u16 = 1;
also where is this used? (it probably should be, as the fact that is wasn't there before and isn't used makes me think a crucial piece of validation is missing)

2024-11-01 19:35 UTC, evan-gray commented on svm/programs/router/src/instructions/register.rs
> +    emit!(IntegratorRegistered {
why are there two events here?

2024-11-01 19:35 UTC, evan-gray commented on svm/programs/router/src/instructions/attest_message.rs
> +        dst_chain: args.dst_chain,
re: the CHAIN_ID comment... where does this instruction check that this is actually the destination chain?

2024-11-01 19:35 UTC, evan-gray commented on svm/tests/router.ts
> +    const borshEvents = borshEventCoder.decode(eventData);
huh... I wish anchor made this a little easier.

2024-11-08 04:30 UTC, bingyuyap commented on svm/tests/router.ts
> +export async function expectIxOk(
updated to async await

2024-11-08 04:30 UTC, bingyuyap commented on svm/package-lock.json
yeah, removed the package-lock.json

2024-11-08 04:30 UTC, bingyuyap commented on svm/package.json
> +    "ts-results": "^3.3.0"
updated to async await to remove this

2024-11-08 04:30 UTC, bingyuyap commented on svm/programs/router/src/instructions/update_admin.rs
> +/// Emits an `AdminUpdated` event
I missed this, added it

2024-11-08 04:31 UTC, bingyuyap commented on svm/programs/router/src/utils/constants.rs
> +pub const SOLANA_CHAIN_ID: u16 = 1;
used cargo feature determine this + added the check on attest_message

2024-11-08 04:31 UTC, bingyuyap commented on svm/programs/router/src/instructions/register.rs
> +    emit!(IntegratorRegistered {
it was a debug emit, removed it

2024-11-08 04:32 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +        dst_chain: args.dst_chain,
added this

2024-11-08 04:33 UTC, bingyuyap commented on svm/tests/router.ts
> +    const borshEvents = borshEventCoder.decode(eventData);
yeah im not exactly sure what the best way is, at least for now i couldn't find any examples to decode cpi events. So over here I just turned it into a regular event to decode it normally

2024-11-08 04:35 UTC, bingyuyap commented on svm/programs/router/src/instructions/update_admin.rs
> -    // Check if there's a pending admin transfer
this is checked in the validate code block

2024-11-08 05:18 UTC, bingyuyap reviewed
I added the `solana-mainnet` `solana-devnet` `solana-localnet`  features to all programs. We can change that to only `router` but it will give this error when running `anchor build -- --features solana-localnet`
```
error: none of the selected packages contains these features: solana-localnet
```

it can be fixed by `anchor build -- --features router/solana-localnet` but not sure if we wanna go that deep

2024-11-13 21:49 UTC, evan-gray requested changes
just quickly reviewed the endpoint program. a few small comments.

2024-11-13 21:49 UTC, evan-gray commented on svm/programs/endpoint/src/lib.rs
> +    if #[cfg(feature = "solana-mainnet")] {
why are the features here `solana-mainnet`, `solana-devnet`, and `solana-localnet`? wouldn't it just be `solana` and potentailly a different chain (like Eclipse or some other SVM in the future)?

2024-11-13 21:49 UTC, evan-gray commented on svm/Anchor.toml
> +mock_integrator = "661Ly6gSCDiGWzC4tKJhS8tqXNWJU6yfbhxNKC4gPF5t"
why change all these public keys?

2024-11-13 21:49 UTC, evan-gray commented on svm/programs/endpoint/src/instructions/add_adapter.rs
> +/// * `args` - The arguments for registering a adapter, including:
not sure how, but looks like some `a adapter` typos came back with this PR

2024-11-13 22:47 UTC, bingyuyap commented on svm/programs/endpoint/src/lib.rs
> +    if #[cfg(feature = "solana-mainnet")] {
i'd imagine that other svm chains to have different `chain_id`s on mainnet and devnet, unlike solana. So just doing this to future prove it

2024-11-13 22:51 UTC, bingyuyap commented on svm/Anchor.toml
> +mock_integrator = "661Ly6gSCDiGWzC4tKJhS8tqXNWJU6yfbhxNKC4gPF5t"
these were the ones that were generated from my keypairs, but i dont think they matter as of now since we are doing local testing

2024-11-13 22:53 UTC, bingyuyap commented on svm/programs/endpoint/src/instructions/add_adapter.rs
> +/// * `args` - The arguments for registering a adapter, including:
should be fixed now

2024-11-14 16:04 UTC, evan-gray commented on svm/programs/endpoint/src/lib.rs
> +    if #[cfg(feature = "solana-mainnet")] {
there's no need to have 3 `solana-*` features here though, so let's not.

2024-11-14 16:50 UTC, evan-gray approved these changes

2024-11-14 17:01 UTC, merged